apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-registry
    app.kubernetes.io/part-of: release-registry
  name: release-registryk7dv
spec:
  path: /
  port:
    targetPort: 8443
  to:
    kind: Service
    name: release-registry
    weight: null
status: {}
