apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-registry
    app.kubernetes.io/part-of: release-registry
  name: release-registry
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: release-registry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: release-registry
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-tmartens-tenant/release-registry/release-registry@sha256:072edafb88643c5d91f33602aacfc5f76e8a1a97194c7155d1ed9ef1d7552bde
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8443
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
